api/urls.py
from django.urls import path
from .views import (
        apiOverview, taskList, taskDetail, taskCreate, taskDelete, taskUpdate, batchList, tasksperbatch,
    )

app_name = 'api'

urlpatterns= [
    path('', apiOverview, name= 'overview'),
    path('task-list/', taskList, name='task-list'),
    path('task-detail/<int:id>/', taskDetail, name='task-detail'),
    path('task-create/', taskCreate, name='task-create'),
    path('task-delete/<int:id>/',taskDelete, name='task-delete'),
    path('task-update/<int:id>/',taskUpdate, name='task-update'),
    path('batch-list/', batchList, name = 'batch-list'),
    path('task-batch/<str:batch>/', tasksperbatch, name='task-batch' ),
]

drf_todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name ='index'),
]

frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'frontend'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index' ),
]

api/models.py
from django.db import models
from django.contrib.auth.models import User

class Batch(models.Model):
    batch = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['-batch']
        verbose_name = 'Batch'
        verbose_name_plural = 'Batches'

    def __str__(self):
        return self.batch.strftime("%B %d, %Y %A")

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(
            max_length = 256,
        )
    completed = models.BooleanField(
            default =  False,
        )
    batch = models.ForeignKey(Batch, related_name = 'tasks', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

frontend/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render
from django.http import JsonResponse
from rest_framework import serializers
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Task, Batch
from .serializers import TaskSerializer, BatchSerializer
import datetime

@api_view(['GET'])
def apiOverview(request):
    api_urls = {
        'List': 'task-list/',
        'Detail': 'task-detail/',
        'Create': 'task-create/',
        'Delete': 'task-create/<int:id>/',
        'Update': 'task-update/<int:id>/',
    }
    return Response(api_urls)


@api_view(['GET'])
def taskList(request):
    batch_today = Batch.objects.get(batch = datetime.date.today())
    tasks = Task.objects.filter(user = request.user, batch_id = batch_today.id).order_by('-id')
    serializer = TaskSerializer(tasks, many =True)
    return Response(serializer.data)


@api_view(['GET'])
def taskDetail(request, id):
    task = Task.objects.get(id= id)
    serializer = TaskSerializer(task, many= False)
    return Response(serializer.data)


@api_view(['POST'])
def taskCreate(request):
    check_batch = Batch.objects.filter(batch = datetime.date.today()).first()
    if check_batch is None:
        check_batch = Batch.objects.create(batch = datetime.date.today())
    serializer = TaskSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save(batch = check_batch, user = request.user)
    return Response(serializer.data)


@api_view(['DELETE'])
def taskDelete(request, id):
    task = Task.objects.get(id = id)
    task.delete()
    return Response("Task was deleted.")


@api_view(['POST'])
def taskUpdate(request, id):
    task = Task.objects.get(id=id)
    serializer = TaskSerializer(instance=task, data=request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)


@api_view(['GET'])
def batchList(request):
    batchlist = Batch.objects.filter(batch__lt = datetime.date.today())
    serializer = BatchSerializer(batchlist, many =True)
    return Response(serializer.data)


@api_view(['GET'])
def tasksperbatch(request, batch):
    tasks = Task.objects.filter(batch = batch, user = request.user)
    serializer = TaskSerializer(tasks, many = True)
    return Response(serializer.data)

frontend/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style type="text/css">
        <style type="text/css">
        body{
          background: rgb(54,217,182);
          background: linear-gradient(90deg, rgba(54,217,182,1) 0%, rgba(32,152,126,1) 43%, rgba(0,212,255,1) 100%);
        }


        h1, h2, h3, h4, h5, p, span, strike{
          font-family: 'Montserrat', sans-serif;

        }


        #task-container{
          max-width:600px;
          margin:0 auto;
          box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
          background-color: #fff;

          margin-top:100px;
          margin-bottom:100px;

          justify-content: space-around;
          align-items: flex-start;

        }

        #form-wrapper{
          position: -webkit-sticky;
          position: sticky;
          top: 0rem;
          border-bottom: 1px solid  #e9e9e9;
          background-color: #fff;
          box-shadow: 0 3px 8px rgba(0,0,0,0.25);
          padding:40px;
        }

        #submit{
          background-color: #36d9b6;
          border-radius: 0;
          border:0;
          color: #fff;
        }

        .flex-wrapper{
            display: flex;
        }

        .task-wrapper{
            margin:5px;
            padding: 5px;
            padding:20px;
            cursor: pointer;
            border-bottom: 1px solid  #e9e9e9;
            color: #686868;
            }

    </style>
    </style>
    <title>Hello, world!</title>
  </head>
  <body>
    <div class="container">

        <div id="task-container">
            <div id="form-wrapper">
                <form id="form">
                    <div class="flex-wrapper">
                        <div style="flex: 6">
                            <input id="title" class="form-control" type="text" name="title" placeholder="Add task">
                        </div>
                        <div style="flex: 1">
                            <input id="submit" class="btn" type="submit" >
                        </div>
                    </div>
                </form>
            </div>

            <div id="list-wrapper">

            </div>
        </div>

    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
    <script type="text/javascript">
        var activeItem = null
        var list_snapshot = []

        renderList()


        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');



        function renderList(){
            var listWrapper = document.getElementById("list-wrapper")
            var url = "{% url 'api:task-list' %}"
            fetch(url)
            .then((resp) => resp.json())
            .then(function(data){
                console.log('Data: ', data)
                var itemList = data
                for (var item in itemList){

                    try{
                        document.getElementById(`data-row-${item}`).remove()
                    }catch(err){

                    }

                    var checkBox = `<input class="form-check-input statuscheckbox" type="checkbox" checked >`
                    if(itemList[item].completed == false){
                        checkBox = `<input class="form-check-input statuscheckbox" type="checkbox" >`
                    }

                    var task = `

                            <div id="data-row-${item}" class="task-wrapper flex-wrapper">
                                <div class="holder" style="flex:7">
                                    <span class="title">${itemList[item].title}</span>
                                </div>
                                <div style="flex: 0">
                                  ${checkBox}
                                </div>
                                <div style="flex:1">
                                    <button class="btn btn-sm btn-outline-info edit">Edit </button>
                                </div>
                                <div style="flex:1">
                                    <button class="btn btn-sm btn-outline-dark delete">-</button>
                                </div>
                            </div>
                    `
                    listWrapper.innerHTML += task
                }

                // for deleting a record - updating list. kasi pag wala to nalilipat lang sa taas ng list ung binura
                if (list_snapshot.length > itemList.length){
                    for (var i = itemList.length; i < list_snapshot.length; i++){
                        document.getElementById(`data-row-${i}`).remove()
                    }
                }

                list_snapshot = itemList

                for (var item in itemList){
                    var editButton = document.getElementsByClassName("edit")[item]
                    var deleteButton = document.getElementsByClassName("delete")[item]
                    var holder = document.getElementsByClassName("holder")[item]
                    var statusBox = document.getElementsByClassName("statuscheckbox")[item]

                    editButton.addEventListener("click", (function(task){
                        return function(){
                            editTask(task)
                        }
                    })(itemList[item]))

                    deleteButton.addEventListener("click", (function(task){
                        return function(){
                            deleteTask(task)
                        }
                    })(itemList[item]))

                    holder.addEventListener("click", (function(task){
                        return function(){
                            taskStatus(task)
                        }
                    })(itemList[item]))

                    statusBox.addEventListener("click", (function(task){
                        return function(){
                            taskStatus(task)
                        }
                    })(itemList[item]))


                }
            })
        }


        function editTask(item){
            activeItem = item
            document.getElementById('title').value = activeItem.title
        }

        function deleteTask(item){
            fetch(`http://localhost:8000/api/task-delete/${item.id}/`,{
                method: 'DELETE',
                headers: {
                           'Content-type': 'application/json',
                           'X-CSRFToken' : csrftoken,
                }
            }).then((response) => {
                    renderList()
            })
        }

        function taskStatus(item){
            url = `http://localhost:8000/api/task-update/${item.id}/`
            item.completed = !item.completed
            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-type': 'application/json',
                    'X-CSRFToken': csrftoken,
                    'data': item,
                },
                body:JSON.stringify({'title':item.title, 'completed':item.completed})
            }).then( function(response){
                renderList()
            })
        }



        var form = document.getElementById("form")
        form.addEventListener('submit', function(e){
            e.preventDefault()
            var url = "{% url 'api:task-create' %}"
            if(activeItem != null ){
                url = `http://localhost:8000/api/task-update/${activeItem.id}/`
                activeItem = null
            }
            var title = document.getElementById('title').value
            fetch(url, {

                method: 'POST',
                headers:{
                    'Content-type': 'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({'title':title})
            }).then(function(response){
                renderList()
                document.getElementById('form').reset()
            })
        })

    </script>
  </body>
</html>

templates/api/sample.html
{% extends 'base.html' %}
{% block content %}

    {% for batch in batches %}
        {{batch}}
    {% endfor %}


{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    {% block styles %}
    {% endblock %}
    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
    <!-- for font awesome -->
    <script src="https://kit.fontawesome.com/13af69944d.js" crossorigin="anonymous"></script>
    {% block scripts %}

    {% endblock %}
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Navbar</a>
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'frontend:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_superuser %}
            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Page</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <button class="btn btn-outline-success" type="submit">{% if user.is_authenticated %}Logout{% else %}Login{% endif %}</button>
      </form>
    </div>
  </div>
  </div>
</nav>